### ISSUE TITLE
Cannot find correct build?

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/arewefastyet#147]
I submitted this job: https://arewefastyet.com/task_info.php?id=94972 that failed with this error:

```
Downloading for repository mozilla-try
Fetching JSON at https://treeherder.mozilla.org/api/project/try/resultset/?full=false&revision=217b7fcf5894
Traceback (most recent call last):
  File "download.py", line 379, in <module>
    options.cset, options.buildtype)
  File "download.py", line 51, in download_for_repo
    urls = creator.find(cset, buildtype=buildtype)
  File "/home/mozilla/arewefastyet/slave/url_creator.py", line 21, in find
    urls = self.url_for_revision(cset, **kwargs)
  File "/home/mozilla/arewefastyet/slave/url_creator.py", line 144, in url_for_revision
    assert len(urls) == 1
AssertionError
Starting benchmark
Failed to get info about output!
Exception: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "execute.py", line 98, in <module>
    info = engineInfo.read_info_file(engine_path)
  File "/home/mozilla/arewefastyet/slave/engineInfo.py", line 7, in read_info_file
    fp = open(path + "info.json", 'r')
IOError: [Errno 2] No such file or directory: 'output/info.json'
```
Comparing to this job, which worked, https://arewefastyet.com/task_info.php?id=94752

It seems like it should have succeeded.

The first API call:
https://treeherder.mozilla.org/api/project/try/resultset/?full=false&revision=217b7fcf5894

We take the top result_set_id: 221495 and go to 
https://treeherder.mozilla.org/api/project/try/jobs/?count=2000&result_set_id=221495

We look for 'build-win32/opt' and find the job guid 784add2b-efa5-4659-bcae-8d67cb02a8e7/0 and go to 
https://treeherder.mozilla.org/api/jobdetail/?job_guid=784add2b-efa5-4659-bcae-8d67cb02a8e7/0

Where we can find target.zip

Is this a bug or did I just not use the tool correctly?

**Comment by bnjbvr** [comment]
Thanks for filing an issue!

This is due to this filter: the changeset indicated in the command line is not the one at the top of the push.
https://github.com/mozilla/arewefastyet/blob/master/slave/url_creator.py#L164-L167

@h4writer, can you explain why this restriction was added in the first place? It feels we could just remove it?

**Comment by h4writer** [comment]
This happens when we commit multiple revisions in one push. Treeherder currently only creates builds for the the full push. I.e. including all revisions. We don't have builds for the revisions in between. 
This test makes sure that we get the build with only that commit. (no extra pushes on top of it). Since we don't have such a build we deliberately fail.

I.e. imagine wanting to bisect performance on the following revision (pushed as one):
rev xxxxx: Part 3: -----, r=
rev xxxxx: Part 2: -----, r=
rev xxxxx: Part 1: -----, r=

Asking for Part 2, will give you a build with Part 3 included. Which would lead to bad bisects!

**Comment by bnjbvr** [comment]
Closing, we're not maintaining this version of AWFY anymore. See https://github.com/mozilla-frontend-infra/js-perf-dashboard for the new frontend.
