### ISSUE TITLE
Add motionmark graph for Firefox nightly

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/arewefastyet#187]
As part of the WebRender project, we'd like to compare Firefox Nightly with the WebRender pref on and off (gfx.webrender.enabled) using [motionmark](http://browserbench.org/MotionMark/)

**Comment by stuartphilp** [comment]
Some more details, when testing the enabled state, we also need to enable:

```gfx.webrender.blob-images```
```image.mem.shared```
and on (Linux only) ```layers.acceleration.force-enabled```

The reference machine is fine for now, and if we have a high end machine (something with a decent graphics card) that would be nice

**Comment by bnjbvr** [comment]
Thanks for opening an issue! Can you open a bugzilla ticket with the following details:

- when should this be enabled? (fwiw I'll be away until January after the work week, so if it's really urgent I could do it this week, otherwise it might have to wait)
- do you want the benchmark to run on 32 bits Firefox? 64 bits Firefox?
- do you want to benchmark other trains, like Beta, etc. or only Nightly?
- do you want to also test Firefox Nightly **without** WebRender?
- do you want to also benchmark other browsers (Chrome)?

Thanks!

**Comment by bnjbvr** [comment]
(also, please cc Bob and me (:bbouvier) on it)

**Comment by bnjbvr** [comment]
I've got a WIP for this. One other question: what's the impact if enable `layers.acceleration.force-enabled` on non-linux platforms?

**Comment by msreckovic** [comment]
As soon as possible to enable.
64-bit Firefox only is fine, nightly only.
Yes, we need to test with and without WebRender so that we can compare
Don't really need to test against Chrome as an ongoing thing
Forcing acceleration on all platforms is fine; it will be a no-op on non-Linux

**Comment by msreckovic** [comment]
Also, once https://bugzilla.mozilla.org/show_bug.cgi?id=1425260 is fixed, we will only need to set gfx.webrender.all preference instead of the three/four mentioned above.
